```{r}
# Import library
library(dplyr)
#library(ggplot2)
#library(tidyverse)
library(janitor)
#library(gganimate)
#library(gifski)
#library(png)
#library(ggrepel)
#library(scales)
#library(reshape2)
#library(xlsx)
library(lubridate)
```

```{r}
path <- "/Users/jason/Documents/GitHub/STAT440/weatherAUS.csv"
df <- read.csv(path)
df
df_tempx <- df %>% 
  filter(month(as.Date(Date)) == 6 & year(as.Date(Date)) == 2016)
df_tempx
```


```{r}
# {Date Location MinTemp MaxTemp}
df_temp <- df %>% select(c(1:4))
# Winter Data
df_temp_winter <- df_temp %>% 
  filter(month(as.Date(Date)) >= 6 & month(as.Date(Date)) <= 8)
df_temp_winter

# Summer Data
df_temp_summer <- df_temp %>% 
  filter(month(as.Date(Date)) == 12 | month(as.Date(Date)) <= 2)
df_temp_summer

# Albury 2016 Winter Data
df_Albury_2016 <- df_temp_winter %>% filter(Location == "Albury" & year(as.Date(Date)) == 2016)
df_Albury_2016

# WaggaWagga 2016 Winter Data
df_WaggaWagga_2016 <- df_temp_winter %>% filter(Location == "WaggaWagga" & year(as.Date(Date)) == 2016)
df_WaggaWagga_2016

# Correlation
cor(df_Albury_2016$MinTemp, df_Albury_2016$MaxTemp)
cor(df_Albury_2016$MaxTemp, df_WaggaWagga_2016$MaxTemp)

```



```{r}
###########
df_temp_9_3 <- df %>% select(c(1:2,20:21))
df_temp_9_3_winter <- df_temp_9_3 %>% 
  filter(month(as.Date(Date)) >= 6 & month(as.Date(Date)) <= 8)
temp_9_3_winter <- df_temp_9_3_winter %>% filter(Location == "Albury" & year(as.Date(Date)) == 2016)
cor(temp_9_3_winter$Temp9am, temp_9_3_winter$Temp3pm, method = "spearman")

lmmm <- lm(Temp3pm ~ Temp9am, data = temp_9_3_winter)
summary(lmmm)$r.squared 

write.csv(df_temp_summer,"/Users/jason/Documents/GitHub/STAT440/df_temp_summer.csv", row.names = FALSE)
```










